### ISSUE TITLE
Al creare usuario en firebase se guarda en lowerCase mientras que el appserver es caseSensitive

### ISSUE THREAD

**Issue by AgustinLeguizamon** [bookbnb-G7/bookbnb-appclient#20]
ejemplo: User@gmail.com 
Firebase lo guarda como user@gmail.com
En el Appserver el body del user queda email:User@gmail.com

Esto provoca que no haya coincidencia entre el email de firebase vs el email del resource User en el AppServer

**Comment by komod0** [comment]
Se arreglo del lado del appserver para que se guarde tambien en minusculas.
